package com.chinatsp.vehicle.controller.semantic

data class Slots(
    val artist: String,
    val song: String,
    val album: String,
    val moreArtist: String,
    val band: String,
    val gender: String,
    val source: String,
    val sourceType: String,
    val genre: String,
    val area: String,
    val lang: String,
    val version: String,
    val season: String,
    val episode: String,
    val mediaSource: String,
    val insType: String,
    val waveband: String,
    val code: String,
    var program: String,
    var name: String,
    var nameOrig: String,
    var presenter: String,
    var tags: String,
    var series: String,
    var location: String,
    var category: String,
    var channel: String,
    var airflowDirection: String,
    var temperature: Any,
    var temperatureGear: Any,
    var fanSpeed: Any,
    var direction: String,
    var mode: String,


    )